name: 'Telegram API issues'

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  action:
    if: contains(github.event.issue.labels.*.name, 'telegram api')
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v4
        with:
          support-label: 'telegram api'
          issue-comment: >
            Please note that **Github issues** should be used only for problems with the library code itself.


            For questions about Telegram API usage, you can search the [API official documentation](https://core.telegram.org/api#getting-started) and the [full list of methods](https://core.telegram.org/methods).

            WTelegramClient covers 100% of the API and let you do anything you can do in an official client.


            If the above links didn't answer your problem, [click here to ask your question on **StackOverflow**](https://stackoverflow.com/questions/ask?tags=c%23+wtelegramclient+telegram-api) so the whole community can help and benefit.
          close-issue: true
          issue-close-reason: 'not planned'
